TesTransaction/TesTransaction/Controllers/PayController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TesTransaction.BL;
using TesTransaction.Models.Transactions;

namespace TesTransaction.Controllers
{
    public class PayController : Controller
    {
        // GET: Pay
        [HandleError]
        [HttpGet]
        public ActionResult Index(string gTot, string nTransac)
        {
            try
            {
                TrPaymentMenuViewModel vm = new TrPaymentMenuViewModel();
                if (string.IsNullOrEmpty(nTransac))
                {
                    ////provisoire
                    //vm.GlobalTotal = "399.97";
                    //vm.NumTransaction = "11";
                    //ViewBag.tot = "399.97";
                    //ViewBag.transac = "11";
                    //ViewBag.ticket = false;
                    throw new NullReferenceException();
                }
                else
                {
                    if (string.IsNullOrEmpty(gTot))
                    {
                        gTot = TransactionBL.FindTotalByTransacId(nTransac);
                    }
                    var listAmounts = PaymentBL.MakeAmountsList(nTransac);
                    if (listAmounts.Count == 0)
                    {
                        vm.GlobalTotal = gTot;
                        ViewBag.tot = gTot;
                        ViewBag.ticket = false;
                    }
                    else
                    {
                        vm.AmountsPaid = listAmounts;
                        decimal result = PaymentBL.AdaptTotalWithPaid(gTot, listAmounts);
                        if (result < 0)
                        {
                            decimal temp = Math.Abs(result);
                            vm.CashReturn = temp.ToString();
                            ViewBag.cashBack = temp.ToString();
                            vm.GlobalTotal = "0";
                            ViewBag.tot = "0";
                            vm.Ticket = TicketBL.FillTicket(nTransac);
                            ViewBag.ticket = true;
                        }
                        else if (result == 0)
                        {
                            ViewBag.cashBack = "0";
                            vm.GlobalTotal = "0";
                            ViewBag.tot = "0";
                            vm.Ticket = TicketBL.FillTicket(nTransac);
                            ViewBag.ticket = true;
                        }
                        else
                        {
                            vm.GlobalTotal = result.ToString();
                            ViewBag.tot = result.ToString();
                            ViewBag.ticket = false;
                        }
                    }
                    vm.NumTransaction = nTransac;
                    ViewBag.transac = nTransac;
                }
                vm.MethodsP = PaymentBL.FindMethodsList();
                ViewBag.messageCard = "";
                return View(vm);
            }
            catch (NullReferenceException ex)
            {
                //to do insert to log file
                var e1 = ex.GetBaseException(); // --> log
                var e4 = ex.Message; // --> log
                var e5 = ex.Source; // --> log
                var e8 = ex.GetType(); // --> log
                var e9 = ex.GetType().Name; // --> log

                ViewBag.Error = "Il n'y a pas de transaction en cours !";
                return View("Error");
            }
            catch (Exception ex)
            {
                //to do insert to log file
                var e1 = ex.GetBaseException(); // --> log
                var e4 = ex.Message; // --> log
                var e5 = ex.Source; // --> log
                var e8 = ex.GetType(); // --> log
                var e9 = ex.GetType().Name; // --> log

                return View("Error");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(string submitButton, TrPaymentMenuViewModel vmodel)
        {
            try
            {
                switch (submitButton)
                {
                    case "Payment":
                        return (Payment(vmodel));

                    case "End":
                        return (EndTransac(vmodel));

                    case "Cancel":
                        return (CancelTransac(vmodel));

                    case "Back":
                        return (BackTransac(vmodel));

                    default:
                        ViewBag.ticket = false;
                        return View(vmodel);
                }
            }
            catch (Exception ex)
            {
                //to do insert to log file
                var e1 = ex.GetBaseException(); // --> log
                var e4 = ex.Message; // --> log
                var e5 = ex.Source; // --> log
                var e8 = ex.GetType(); // --> log
                var e9 = ex.GetType().Name; // --> log

                return View("Error");
            }
        }

        private ActionResult Payment(TrPaymentMenuViewModel vmodel)
        {
            if (ModelState.IsValid)
            {
                TrPaymentMenuViewModel vm = new TrPaymentMenuViewModel();
                switch (vmodel.MethodP)
                {
                    //method cash
                    case "1":
                        return (PayCash(vmodel));

                    //method debit card
                    case "2":
                        //simulation
                        if (vmodel.PayCardConfirmed)
                        {
                            return (PayCardDebit(vmodel));
                        }
                        return (PayCardDebitNotConfirmed(vmodel));

                    //method credit card
                    case "3":
                        ////simulation same process CardDebit
                        //return (PayCardCredit(vmodel));
                        if (vmodel.PayCardConfirmed)
                        {
                            return (PayCardDebit(vmodel));
                        }
                        return (PayCardDebitNotConfirmed(vmodel));

                    //method voucher
                    case "4":
                        //same process PayCash
                        return (PayCash(vmodel));

                    default:
                        ViewBag.tot = vmodel.GlobalTotal;
                        ViewBag.amount = vmodel.Amount;
                        ViewBag.cashBack = vmodel.CashReturn;
                        vmodel.MethodsP = PaymentBL.FindMethodsList();
                        ViewBag.messageCard = "";
                        ViewBag.ticket = false;
                        return View(vmodel);
                }
            }
            vmodel.MethodsP = PaymentBL.FindMethodsList();
            ViewBag.tot = vmodel.GlobalTotal;
            ViewBag.amount = vmodel.Amount;
            ViewBag.cashBack = vmodel.CashReturn;
            ViewBag.messageCard = "";
            ViewBag.ticket = false;
            return View(vmodel);
        }


        private ActionResult EndTransac(TrPaymentMenuViewModel vmodel)
        {
            if (vmodel.GlobalTotal == "0")
            {
                //to do --> print ticket  ???

                //to do --> add n° ticket & close transaction
                TransactionBL.AddTicketAndCloseTransac(vmodel.NumTransaction);
                return RedirectToAction("Transaction", "Home");
            }
            vmodel.MethodsP = PaymentBL.FindMethodsList();
            ViewBag.nopay = "La transaction n'est pas payée!";
            ViewBag.tot = vmodel.GlobalTotal;
            ViewBag.amount = vmodel.Amount;
            ViewBag.cashBack = vmodel.CashReturn;
            ViewBag.ticket = false;
            return View(vmodel);
        }

        private ActionResult CancelTransac(TrPaymentMenuViewModel vmodel)
        {
            if (string.IsNullOrEmpty(vmodel.NumTransaction))
            {
                //to do --> ???
                return RedirectToAction("Transaction", "Home");
            }
            else
            {
                TransactionBL.CancelTransac(vmodel.NumTransaction);
                return RedirectToAction("Transaction", "Home");
            }
        }

        private ActionResult BackTransac(TrPaymentMenuViewModel vmodel)
        {

            return RedirectToAction("TransacReturn", "Transaction", vmodel);
        }

        private ActionResult PayCash(TrPaymentMenuViewModel vmodel)
        {
            var temp = vmodel.Amount.Replace(".", ",");
            decimal cash = decimal.Parse(temp);
            // legal limit for cash
            if (cash <= 3000)
            {
                PaymentBL.CalculCash(vmodel);
            }
            else
            {
                @ViewBag.limitCash = "Montant cash max de 3000 € dépassé !";
            }
            ViewBag.tot = vmodel.GlobalTotal;
            ViewBag.amount = vmodel.Amount;
            ViewBag.cashBack = vmodel.CashReturn;
            vmodel.MethodsP = PaymentBL.FindMethodsList();
            vmodel.AmountsPaid = PaymentBL.MakeAmountsList(vmodel.NumTransaction);
            ViewBag.messageCard = "";
            if (ViewBag.tot == "0")
            {
                vmodel.Ticket = TicketBL.FillTicket(vmodel.NumTransaction);
                ViewBag.NumT = vmodel.Ticket.Ticket;
                vmodel.NumTicket = vmodel.Ticket.Ticket;
                ViewBag.ticket = true;
            }
            else
            {
                ViewBag.ticket = false;
            }
            return View(vmodel);
        }

        private ActionResult PayCardDebit(TrPaymentMenuViewModel vmodel)
        {
            PaymentBL.CalculCash(vmodel);
            ViewBag.tot = vmodel.GlobalTotal;
            ViewBag.amount = vmodel.Amount;
            ViewBag.cashBack = vmodel.CashReturn;

TesTransaction/TesTransaction/Views/Pay/Index.cshtml
@using TesTransaction.Models.Transactions
@model  TrPaymentMenuViewModel

@{
    ViewBag.Title = "PaymentMenu";
}

@section Styles {
    <link href="@Url.Content("~/Content/test2.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/ticketprint.css")" rel="stylesheet" type="text/css" media="print" />
}

@section Scripts{
    <script src="@Url.Content("~/Scripts/pos2.js")" type="text/javascript"></script>
}


<h2 style="color: red; font-weight: bold">@ViewBag.nopay</h2>
<h2 style="color: red; font-weight: bold">@ViewBag.Error</h2>

<div id="pagepay">
    <div id="noprintpart">
        @using (Html.BeginForm("Index", "Pay", FormMethod.Post))
        {
            @Html.AntiForgeryToken()

            <div id="navButton" class="navbar">
                <ul class="nav nav-pills nav-justified">
                    @if (ViewBag.ticket)
                    {
                        <li class="nav-item"><input type="submit" name="submitButton" class="btn btn-outline" value="End"></li>
                        <li class="nav-item"><input type="submit" name="submitButton" class="btn btn-danger" value="Cancel" disabled></li>
                        <li class="nav-item"><input type="submit" name="submitButton" class="btn btn-outline" value="Back" disabled></li>
                    }
                    else
                    {
                        <li class="nav-item"><input type="submit" name="submitButton" class="btn btn-outline" value="End" disabled></li>
                        <li class="nav-item"><input type="submit" name="submitButton" class="btn btn-danger" value="Cancel" onclick="return confirm('Etes-vous sur de vouloir supprimer la transaction?');"></li>
                        <li class="nav-item"><input type="submit" name="submitButton" class="btn btn-outline" value="Back" onclick="return confirm('Voulez-vous retourner à la transaction?');"></li>
                    }
                </ul>
            </div>
            <div style="visibility:visible">
                @Html.LabelFor(m => m.NumTransaction)
                @Html.TextBoxFor(m => m.NumTransaction, new { size = "3", @readonly = "readonly" })
                @Html.ValidationMessageFor(m => m.NumTransaction, "", new { @class = "text-danger" })
                <div style="visibility:hidden">
                    @Html.TextBoxFor(m => m.NumTicket, new { @Value = ViewBag.NumT, size = "3", @readonly = "readonly" })
                    @Html.ValidationMessageFor(m => m.NumTicket, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="containerPay">
                <div class="cellPay">
                    <h2>@Html.LabelFor(m => m.GlobalTotal)</h2>
                    <div>
                        @if (ViewBag.tot == "0")
                        {
                            @Html.TextBoxFor(m => m.GlobalTotal, new { @Value = ViewBag.tot, @class = "totToPay", @readonly = "readonly", @style = "border-color:green" })
                        }
                        else
                        {
                            @Html.TextBoxFor(m => m.GlobalTotal, new { @Value = ViewBag.tot, @class = "totToPay", @readonly = "readonly" })
                        }
                    </div>
                    @Html.ValidationMessageFor(m => m.GlobalTotal, "", new { @class = "text-danger" })
                </div>

                <div class="cellPay">
                    <h2>@Html.LabelFor(m => m.CashReturn)</h2>
                    <div>
                        @if (ViewBag.cashBack == "0" || ViewBag.cashBack == "" || ViewBag.cashBack == null)
                        {
                            <div>
                                @Html.TextBoxFor(m => m.CashReturn, new { @Value = ViewBag.cashBack, @class = "totToPay", @readonly = "readonly", @style = "border-color:green" })
                            </div>
                        }
                        else
                        {
                            <div>
                                @Html.TextBoxFor(m => m.CashReturn, new { @Value = ViewBag.cashBack, @class = "totToPay", @readonly = "readonly" })
                            </div>
                        }
                        @Html.ValidationMessageFor(m => m.CashReturn, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div> <!-- end containerPay -->
            <div class="containerPay">
                <div class="cellPay">
                    <h2>@Html.LabelFor(m => m.Amount)</h2>
                    <p style="color:red">@ViewBag.limitCash</p>
                    <div>
                        @Html.TextBoxFor(m => m.Amount, new { @Value = ViewBag.amount, @class = "totToPay", @style = "border-color:silver" })
                    </div>
                    @Html.ValidationMessageFor(m => m.Amount, "", new { @class = "text-danger" })
                </div>
                <div class="cellPay">
                    <h2>@Html.LabelFor(m => m.AmountsPaid)</h2>
                    <p style="color:red"> </p>
                    <div>
                        @if (Model.AmountsPaid != null)
                        {
                            <ol class="totToPayList">
                                @for (int i = 0; i < Model.AmountsPaid.Count; i++)
                                {
                                    <li>@Model.AmountsPaid[i]<span class="glyphicon glyphicon-euro"></span></li>
                                }
                            </ol>
                        }
                    </div>
                    @Html.ValidationMessageFor(m => m.AmountsPaid, "", new { @class = "text-danger" })
                </div>
            </div> <!-- end containerPay -->

            <div id="paymentMethods">
                <h2>@Html.LabelFor(m => m.MethodP)</h2>
                <div>
                    @Html.DropDownListFor(m => m.MethodP, new SelectList(Model.MethodsP, "idPaymentMethod", "method"), "Choix de la méthode de paiment")
                    @Html.ValidationMessageFor(m => m.MethodP, "", new { @class = "text-danger" })
                </div>
            </div>
            <div id="paymentZone">
                @if (!ViewBag.ticket)
                {
                    <div><input type="submit" name="submitButton" class="btn btn-outline" value="Payment"></div>

                    if (Model.PayCardToConfirm)
                    {
                        <div id="divCardConfirmed">@Html.LabelFor(m => m.PayCardConfirmed, new { @class = "custom-control-label" })</div>
                        <div>@Html.CheckBoxFor(m => m.PayCardConfirmed, new { @class = "custom-control-input" })</div>

                    }
                }
            </div>
        }
    </div>
    @if (ViewBag.ticket)
    {
        <div id="myTicket">
            @Html.Partial("_PartialTicket", Model.Ticket)
        </div>
        <div id="optionsTicket">

        </div>
    }
</div>

TesTransaction/TesTransaction/Views/Pay/_PartialTicket.cshtml
@model TesTransaction.Models.Transactions.TrTicketViewModel

@{

    Layout = null;

}

<!--  -->
<!-- Logo Magasin -->
<div style="text-align: center;">
    <img src="~/Content/image/logo_magasin.png" alt="logo du magasin">
</div>

<div class="container">
    <!-- Date et heure-->
    <div class="row">
        <div class="col-md-2">
            @Html.LabelFor(m => m.DateTicket)
        </div>
        <div class="col-md-2 offset-md-2">
            @Html.DisplayFor(m => m.DateTicket)
            @Html.ValidationMessageFor(m => m.DateTicket, "", new { @class = "text-danger" })
        </div>
    </div>
    <!-- N° Transac -->
    <div class="row">
        <div class="col-md-2">
            @Html.LabelFor(m => m.Transaction)
        </div>
        <div class="col-md-2 offset-md-2">
            @Html.DisplayFor(m => m.Transaction)
            @Html.ValidationMessageFor(m => m.Transaction, "", new { @class = "text-danger" })
        </div>
    </div>
</div>
<!-- coordonnées magasin -->
<div style="text-align: center;">
    <p>Nom du magasin</p>
    <p>rue du magasin</p>
    <p>ville</p>
    <p>Tel</p>
    <p>email</p>
    <p>heures d'ouverture</p>
</div>

<!-- liste des articles -->
<div>
    <table class="table table-condensed" id="tableDetail">
        <tr>
            <th>Produit</th>
            <th>Prix</th>
            <th>Quantité</th>
            <th>Total</th>
        </tr>
        @{
            if (Model.DetailsListWithTot == null || Model.DetailsListWithTot.Count == 0)
            {
                <tr>
                    <td>-</td>
                    <td>-</td>
                    <td>-</td>
                    <td>-</td>
                </tr>
            }
            else
            {
                foreach (var item in Model.DetailsListWithTot)
                {
                    <tr>
                        <td id="nameItem">@item.ProductName</td>
                        <td id="price">@item.Price</td>
                        <td id="quantity">@item.Quantity</td>
                        <td id="itemSubTot">@item.TotalItem</td>
                    </tr>
                }
            }
        }
    </table>
</div>

<div class="container">
    <!-- remise -->
    <div class="row">
        <div class="col-md-2">
            @Html.LabelFor(m => m.DiscountG)
        </div>
        <div class="col-md-2 offset-md-2">
            @Html.DisplayFor(m => m.DiscountG)
            @Html.ValidationMessageFor(m => m.DiscountG, "", new { @class = "text-danger" })
        </div>
    </div>
    <!-- TVA -->
    <div class="row">
        <div class="col-md-2">
            @Html.LabelFor(m => m.VatG)
        </div>
        <div class="col-md-2 offset-md-2">
            @Html.DisplayFor(m => m.VatG)
            @Html.ValidationMessageFor(m => m.VatG, "", new { @class = "text-danger" })
        </div>
    </div>
    <!-- total -->
    <div class="row">
        <div class="col-md-2">
            @Html.LabelFor(m => m.TotalG)
        </div>
        <div class="col-md-2 offset-md-2">
            @Html.DisplayFor(m => m.TotalG)
            @Html.ValidationMessageFor(m => m.TotalG, "", new { @class = "text-danger" })
        </div>
    </div>
</div>
<!-- methodes de paiment -->
<!-- montant -->
<div>
    <table class="table table-condensed" id="tablePayment">
        <tr>
            <th>Methode</th>
            <th>Montant</th>
        </tr>
        @{
            if (Model.Payments == null || Model.Payments.Count == 0)
            {
                <tr>
                    <td>-</td>
                    <td>-</td>
                </tr>
            }
            else
            {
                foreach (var item in Model.Payments)
                {
                    <tr>
                        <td id="nameItem">@item.paymentMethodId</td>
                        <td id="price">@item.amount<span class="glyphicon glyphicon-euro"></span></td>
                    </tr>
                }
            }
        }
    </table>
</div>
<!-- message -->
<div>
    <p id="messageT">
        @Html.DisplayFor(m => m.Message)
    </p>
    @Html.ValidationMessageFor(m => m.Message, "", new { @class = "text-danger" })
</div>