TesTransaction/TesTransaction/Controllers/CashController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TesTransaction.Data.Entity;

namespace TesTransaction.Controllers
{
    public class CashController : Controller
    {
        private TestTransactionEntities db = new TestTransactionEntities();

        // GET: Cash
        public ActionResult Index(string sortOrder, DateTime? searchString)
        {
            ViewBag.DateSortParam = String.IsNullOrEmpty(sortOrder) ? "date_desc" : "";
            var cashD = db.CASH_BOTTOM_DAYs.Include(c => c.TERMINAL);
            if (!String.IsNullOrEmpty((searchString).ToString()))
            {
                cashD = cashD.Where(s => s.dateDay == searchString);
            }
            switch (sortOrder)
            {
                case "date_desc":
                    cashD = cashD.OrderByDescending(d => d.dateDay);
                    break;
                default:
                    cashD = cashD.OrderBy(d => d.dateDay);
                    break;
            }

            return View(cashD.ToList());
        }

        // GET: Cash/Details/5
        public ActionResult Details(DateTime id1, int? id2)
        {
            if (id1 == null || id2 == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CASH_BOTTOM_DAY cashD = db.CASH_BOTTOM_DAYs.Find(id1, id2);
            if (cashD == null)
            {
                return HttpNotFound();
            }
            return View(cashD);
        }

        // GET: Cash/Create
        public ActionResult Create()
        {
            ViewBag.terminalId = new SelectList(db.TERMINALs, "idTerminal", "nameTerminal");
            return View();
        }

        // POST: Cash/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "dateDay,terminalId,beginningCash")] CASH_BOTTOM_DAY cashDay)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    db.CASH_BOTTOM_DAYs.Add(cashDay);
                    db.SaveChanges();
                    Session["sessTerminalId"] = cashDay.terminalId;
                    return RedirectToAction("Index", "Transaction");
                }
                catch (Exception ex)
                {
                    //to do insert to log file
                    var e1 = ex.GetBaseException(); // --> log
                    var e4 = ex.Message; // --> log
                    var e5 = ex.Source; // --> log
                    var e8 = ex.GetType(); // --> log
                    var e9 = ex.GetType().Name; // --> log

                    ViewBag.Error = "Il existe déjà un fond de caisse sur ce terminal pour cette date";
                    ViewBag.terminalId = new SelectList(db.TERMINALs, "idTerminal", "nameTerminal", cashDay.terminalId);
                    return View(cashDay);
                }

            }
            ViewBag.terminalId = new SelectList(db.TERMINALs, "idTerminal", "nameTerminal", cashDay.terminalId);
            return View(cashDay);
        }

        // GET: Cash/Edit/5
        //id1 = dateday   id2 = terminalId
        public ActionResult Edit(DateTime id1, int? id2)
        {
            if (id1 == null || id2 == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CASH_BOTTOM_DAY cashD = db.CASH_BOTTOM_DAYs.Find(id1, id2);
            if (cashD == null)
            {
                return HttpNotFound();
            }
            ViewBag.terminalId = new SelectList(db.TERMINALs, "idTerminal", "nameTerminal", cashD.terminalId);
            return View(cashD);
        }

        // POST: Cash/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "dateDay,terminalId,beginningCash,endCash")] CASH_BOTTOM_DAY cashD)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cashD).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.terminalId = new SelectList(db.TERMINALs, "idTerminal", "nameTerminal", cashD.terminalId);
            return View(cashD);
        }

        // GET: Cash/Delete/5
        public ActionResult Delete(DateTime id1, int? id2)
        {
            if (id1 == null || id2 == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CASH_BOTTOM_DAY cashD = db.CASH_BOTTOM_DAYs.Find(id1, id2);
            if (cashD == null)
            {
                return HttpNotFound();
            }
            return View(cashD);
        }

        // POST: Cash/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(DateTime id1, int? id2)
        {
            CASH_BOTTOM_DAY cashD = db.CASH_BOTTOM_DAYs.Find(id1, id2);
            db.CASH_BOTTOM_DAYs.Remove(cashD);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: Cash/End
        public ActionResult End()
        {
            var id1 = DateTime.Today;
            var id2 = Session["sessTerminalId"];
            if (id1 == null || id2 == null)
            {
                //return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                TempData["Error"] = "Le terminal n'a pas été trouvé, existe-t-il un fond de caisse sur ce terminal pour cette date?";
                return RedirectToAction("Transaction", "Home");
            }
            CASH_BOTTOM_DAY cashD = db.CASH_BOTTOM_DAYs.Find(id1, id2);
            if (cashD == null)
            {
                return HttpNotFound();
            }
            ViewBag.terminalId = new SelectList(db.TERMINALs, "idTerminal", "nameTerminal", cashD.terminalId);
            return View(cashD);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult End([Bind(Include = "dateDay,terminalId,beginningCash,endCash")] CASH_BOTTOM_DAY cashD)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    db.Entry(cashD).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    //to do insert to log file
                    var e1 = ex.GetBaseException(); // --> log
                    var e4 = ex.Message; // --> log
                    var e5 = ex.Source; // --> log
                    var e8 = ex.GetType(); // --> log
                    var e9 = ex.GetType().Name; // --> log

                    ViewBag.Error = "??";
                }
            }
            ViewBag.terminalId = new SelectList(db.TERMINALs, "idTerminal", "nameTerminal", cashD.terminalId);
            return View(cashD);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TesTransaction/TesTransaction/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TesTransaction.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult Transaction()
        {
            if (TempData["Error"] == null)
            {
                return View("Transaction");
            }
            else
            {
                ViewBag.Error = TempData["Error"].ToString();
                return View("Transaction");
            }
        }
    }
}

TesTransaction/TesTransaction/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

TesTransaction/TesTransaction/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

TesTransaction/TesTransaction/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

@section Styles {
    <link href="@Url.Content("~/Content/test2.css")" rel="stylesheet" type="text/css" />
}

<div class="jumbotron">
    <h1>MyPOS</h1>
</div>

<div class="row">
    <div class="col-md-6">
        <h2 class="titles">Transactions</h2>
        <div class="titlesButtons">
            <button type="button" class="btn btn-default menuButton" onclick="location.href='@Url.Action("Transaction", "Home")'" style="font-size: xx-large">Go &raquo;</button>
        </div>
    </div>
    <div class="col-md-6">
        <h2 class="titles">Gestion</h2>
        <div class="titlesButtons">
            <button type="button" class="btn btn-default menuButton" onclick="location.href='@Url.Action("Transaction", "Home")'" style="font-size: xx-large" disabled>Go &raquo;</button>
        </div>
    </div>
</div>

TesTransaction/TesTransaction/Views/Home/Transaction.cshtml
@{
    ViewBag.Title = "Transaction";
}

@section Styles {
    <link href="@Url.Content("~/Content/test2.css")" rel="stylesheet" type="text/css" />
}

<h2>Transaction</h2>

<p>
    @Html.ActionLink("Back to Home", "Index", "Home")
</p>

<span class="text-danger">@ViewBag.Error</span>

<div class="container">
    <div class="row">
        <h4>Menu</h4>
        <div class="jumbotron menuTransac">
            <div>
                <button type="button" class="btn btn-primary menuButton" onclick="location.href='@Url.Action("Create", "Cash")'">Créer un </br>fond de caisse</button>
            </div>
            <div>
                <button type="button" class="btn btn-primary menuButton" onclick="location.href='@Url.Action("Index", "Transaction")'">Nouvelle</br>Transaction</button>
            </div>
            <div>
                <button type="button" class="btn btn-primary menuButton" onclick="location.href='@Url.Action("Index", "Cash")'" disabled>Vider la </br> caisse</button>
            </div>
            <div>
                <button type="button" class="btn btn-primary menuButton" onclick="location.href='@Url.Action("End", "Cash")'">Cloturer le </br>fond de caisse</button>
            </div>
        </div>
        <div class="jumbotron menuTransac">
            <div>
                <button type="button" class="btn btn-primary menuButton" onclick="location.href='@Url.Action("Index", "Cash")'">Consulter les </br> fonds de caisse</button>
            </div>
            <div>
                <button type="button" class="btn btn-primary menuButton" onclick="location.href='@Url.Action("Index", "Cash")'" disabled>Ré-imprimer </br> un ticket</button>
            </div>
            <div>

            </div>
            <div>

            </div>
            <div>

            </div>
        </div>
    </div>
</div>